### ISSUE TITLE
maintain words in `.spelling` sorted alphabetically

### ISSUE THREAD

**Issue by andyli** [lukeapage/node-markdown-spellcheck#83]
Feature request:
Can the CLI keeps the words in `.spelling` sorted alphabetically?
It would be easier to read.

**Comment by dreh23** [comment]
Maybe this is useful. We have a Makefile target like this:

```
format-spelling:
        sort < .spelling | sort | uniq | tee .spelling.tmp > /dev/null && mv .spelling.tmp .spelling
```

A bit hacky, but works.

**Comment by agilgur5** [comment]
Some other workaround scripts from https://github.com/argoproj/argo-workflows/pull/12521:

Simple version:
```sh
cat .spelling | sort | uniq | tee .spelling > /dev/null
```

More complex skipping a few comments at the top of the file:
```bash
# alphabetize spelling file -- ignore first 5 lines (comments), then sort the rest case-sensitive and remove duplicates
cat .spelling | awk 'NR<6{ print $0; next } { print $0 | "sort" }' | uniq | tee .spelling > /dev/null
```

**Comment by martyzz1** [comment]
I use this pre-commit hook - https://pre-commit.com/

```
- repo: https://github.com/trussworks/pre-commit-hooks
      rev: v1.1.1
      hooks:
        - id: mdspell
          name: Spell checking md files. Add exception words to .spelling
▎         args: ['--en-gb', '--report', '--ignore-numbers', '--ignore-acronyms']
 - repo: https://github.com/martyzz1/pre-commit-hooks
      rev: v2.1.38
      hooks:
        - id: sort-insensitive
          stages: [pre-commit]
          files: \.spelling$
 
```
